### ISSUE TITLE
Perhaps release 6.* to hackage?

### ISSUE THREAD

**Issue by mdorman** [creichert/bencode#1]
The current 5.\* release isn't compatible with ghc-7.10; I have a backport of the necessary patch from 6.*. if for some reason you would prefer to release that.

**Comment by creichert** [comment]
Do you have any changes in addition to these patches? 

https://github.com/creichert/bencode/commit/a6f3ae8eda9a9ac2740a2884e1ea56ed93f5f7b4
https://github.com/creichert/bencode/commit/597163b497e853d553b04db99c4b9342ce7d5d80

I'm a bit confused on what you mean by backporting but I'm happy to integrate patches and upload a new version. I'm removing some of the redundant tests now and I'll flag Lemmih to review the changes.

Thanks!

**Comment by creichert** [comment]
New version uploaded to Hackage: https://hackage.haskell.org/package/bencode-0.6.0.0

If you have any further patches you want to add I'll be happy to integrate them.

Thanks again!

**Comment by mdorman** [comment]
Hey, sorry if I wasn't clear before.  The patch needed to compile 5.\* with 7.10 would only apply with fuzz---so when I meant backport, I really just meant "regen against 5._".  But getting 6._ out is plenty.  Thanks.
