### ISSUE TITLE
bencode-0.6.0.0: build failure with ghc 8.8.1

### ISSUE THREAD

**Issue by peti** [creichert/bencode#16]
bencode-0.6.0.0 ships a broken `Setup.hs` file:

~~~
Setup.lhs:5:31: error:
    Variable not in scope: defaultUserHooks :: UserHooks
  |
5 | > main = defaultMainWithHooks defaultUserHooks
  |                               ^^^^^^^^^^^^^^^^
~~~

You can simply delete that file from the release tarball since your package is of `BuildType: Simple` anyway.

**Comment by peti** [comment]
Unfortunately, there is another problem once you get past that:

~~~
src/Data/BEncode/Parser.hs:64:5: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
   |
64 |     fail str = BParser $ \_ -> Error str
   |     ^^^^
~~~

**Comment by peti** [comment]
Ping?

**Comment by creichert** [comment]
@peti These fixes are on my agenda but I've been quite busy so if you have any suggestions to make the patches easier that would help. Hoping to have time to fix before this weekend.

Thank you.

**Comment by peti** [comment]
> If you have any suggestions to make the patches easier that would help.

https://github.com/creichert/bencode/pull/17

**Comment by peti** [comment]
Ping? Will you release a new version?

**Comment by creichert** [comment]
@peti I've given you permissions on Hackage and GitHub. Thank you.
