### ISSUE TITLE
list parser should not require name parameter

### ISSUE THREAD

**Issue by matthewleon** [creichert/bencode#2]
The list parser currently is based on the dictionary parser and requires a `String` name parameter. This prevents parsing lists of lists, which are used in, for example, BEP-12: http://bittorrent.org/beps/bep_0012.html

**Comment by matthewleon** [comment]
Relevant code from: https://github.com/creichert/bencode/blob/master/src/Data/BEncode/Parser.hs

```
list :: String -> BParser a -> BParser [a]
list name p
    = dict name >>= \lst ->
      BParser $ \b -> case lst of
                      BList bs -> foldr (cat . runB p) (Ok [] b) bs
                      _ -> Error $ "Not a list: " ++ name
    where cat (Ok v _) (Ok vs b) = Ok (v:vs) b
          cat (Ok _ _) (Error str) = Error str
          cat (Error str) _ = Error str
```

Type signature should simply be `BParser a -> BParser [a]`

**Comment by creichert** [comment]
I agree that we should support this. I just pushed a test suite so it
will be easier to implement and verify new changes.

This is an extension to the standard, right? Is the current list parser
implemented incorrectly according to the standard? I'm basically
wondering how we might support BEP's without breaking the current
interface, if possible.

Is this something you're interested in taking a crack at? It would be
nice to get a sample test input/output either way.

Thanks!

**Comment by matthewleon** [comment]
Hi Christopher,

The BEP is an extension to the BitTorrent standard. The bencoding standard (specified here, though I'm not sure this is an official document: https://wiki.theory.org/BitTorrentSpecification#Bencoding) is unaffected by the change.

The current list implementation is incorrect according to the standard, because it requires a list to be a value of a dictionary, whereas according to the spec lists can be a recursive structure.

I would indeed be happy to fix the implementation. My approach would probably be to make a new list parsing function and deprecate the old one, to protect legacy codebases.

That being said, I want to make sure that maintaining this project makes sense. I see that there is a "competing" implementation here: http://hackage.haskell.org/package/bencoding

That implementation (bencoding) claims to be fast (haven't checked), should support generic serialization, and should implement list parsing to spec. If all these claims are true, it would seem to me that bencode should be deprecated in favor of bencoding.

But it's quite possible I'm missing something here. It seems that your package is still getting more downloads on hackage. Can you clarify the situation? Perhaps @pxqr can?

**Comment by creichert** [comment]
Maintaining this project makes sense to me as there are projects like
`git-annex` which depend on it (through the `torrent` package) and it's
actively maintained (by me) in several distributions.

This package predates `bencoding` by several years and is designed to
have a lean dependency profile and a simple API.

I don't know whether this package is "better" than any other
implementation but I will be happy to make performance improvements and
help fix bugs on this implementation.

I'm not sure why you are suggesting deprecation but I have no plans to
drop it in favor of another package.

I added encoding/decoding tests to the Spec for nested lists from the
`Data.BEncode` module. They aren't actually testing the
`Data.BEncode.Parser.list` function yet..

https://github.com/creichert/bencode/blob/master/tests/Spec.hs#L26

**Comment by matthewleon** [comment]
What you're saying makes sense. I'll go ahead and try to implement this tonight.

**Comment by pxqr** [comment]
@matthewleon, I can't remember any restrictions on nesting, so you can nest lists into lists or dictionaries into lists, e.t.c.  Bencode is supposed to be recursive just like for e.g. json.

The `bencoding` package is built mostly for purposes of the `bittorrent` package and it was written years after `bencode`. So they may differ largely, indeed.
