### ISSUE TITLE
Are the combinators in Data.BEncode.Parser actually parsers?

### ISSUE THREAD

**Issue by matthewleon** [creichert/bencode#7]
I'm inclined to say that the data one accesses through these "parsers" is already parsed by the combinators in Data.BEncode. The name "parser" at this point seems like a holdover. Can we think of a more appropriate name? Accessors? Getters?

Is it worth renaming things? Or should there just be an explanatory note?

**Comment by matthewleon** [comment]
I'm inclined, upon further thought, to say that the BParser monad might just be a Reader monad in disguise. Thoughts?

**Comment by creichert** [comment]
I'm still thinking about this one. I agree with what you are saying but
I'm hesitant to make the change without a clear path to more
improvements in the interface. I think an explanation would be a good
idea at this point.

**Comment by matthewleon** [comment]
There's a branch in my repo, https://github.com/matthewleon/bencode/tree/reader that tries to implement this in https://github.com/matthewleon/bencode/blob/reader/src/Data/BEncode/Reader.hs

I'll probably follow this idea to its conclusion for entertainment purposes at least, but not sure it's worth the change.

**Comment by creichert** [comment]
I like it. If it works and is an improvement I wouldn't have a problem merging it. I think it would be a good idea to properly deprecate the old module, though (if it's at all possible).

**Comment by matthewleon** [comment]
Still working on it. Made some big improvements. It will indeed work, and well. My current idea is just to leave the old `BParser` as is, mark it as deprecated, and have the hot new (documented) thing be `BReader`.

Just working on documentation right now.

**Comment by creichert** [comment]
On Fri, Jul 24 2015, Matthew Leon notifications@github.com wrote:

> Still working on it. Made some big improvements. It will indeed work,
> and well. My current idea is just to leave the old `BParser` as is,
> mark it as deprecated, and have the hot new (documented) thing be
> `BReader`.

Cool, looking forward to it.

I think proper deprecation is the best idea. It reduces unexpected
breakage, at least.

> Just working on documentation right now.

Perfect.
